//world_management = true
zones {
  safe_zone {
    blacklisted_entities = [
      zombie, skeleton, spider, creeper, drowned
    ]
  }
  server_safe_zone {
    blacklisted_entities = [
      wolf, horse
    ]
  }
}